name: Build and Upload Artifact

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # This triggers the workflow when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Artifact file
        run: |
          mkdir output
          echo "This is a sample artifact file" > output/hello.txt

      - name: Upload Artifact to Actions
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/
          retention-days: 14

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/hello.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

