name: Build and Upload Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Artifact file
        run: |
          mkdir output
          echo "This is a sample artifact file" > output/hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/
          retention-days: 14
